export { default as HeroSection } from './HeroSection.vue'
export { default as AboutSection } from './AboutSection.vue'
export { default as ExperienceSection } from './ExperienceSection.vue'
export { default as ProjectsSection } from './ProjectsSection.vue'
export { default as ContactSection } from './ContactSection.vue'
